micronaut:
  application:
    name: sample123
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}
datasources:
  default:
    driverClassName: org.postgresql.Driver
    db-type: postgresql
    schema-generate: CREATE_DROP
    dialect: POSTGRES
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        connection:
          url: jdbc:postgresql://localhost:5432/postgres
          username: postgres
          password: ''
    reactive: true
netty:
  default:
    allocator:
      max-order: 3
